//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDatabase.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Client
    {
        public int ID { get; set; }
        [Required]
        [StringLength(30)]
        public string Name { get; set; }
        [Required]
        [StringLength(300)]
        public string Address { get; set; }
        [Required]
        [StringLength(300)]
        public string Postcode { get; set; }
        public string TelephoneNo { get; set; }
        [Required]
        [StringLength(30000)]
        public string Capacity { get; set; }
        [Display(Name = "DoB")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DoB { get; set; }
        [Required]
        [StringLength(300)]
        public string Gender { get; set; }
        [Required]
        [StringLength(30)]
        public string Height { get; set; }
        [Required]
        [StringLength(30)]
        public string Weight { get; set; }
        [Required]
        [StringLength(300)]
        public string GP { get; set; }
        [Required]
        [StringLength(300)]
        public string Dentist { get; set; }
        [Required]
        [StringLength(300)]
        public string HospitalOrCentre { get; set; }
        [Required]
        [StringLength(300)]
        public string Consultant { get; set; }
        [Required]
        [StringLength(3000)]
        public string OtherHealthAgencies { get; set; }
        [Required]
        [StringLength(30000)]
        public string PersonalHistory { get; set; }
        [Required]
        [StringLength(30000)]
        public string HealthAndPhysicalNeeds { get; set; }
        [Required]
        [StringLength(30000)]
        public string Mobility { get; set; }
        [Required]
        [StringLength(30000)]
        public string MedicalCareInformation { get; set; }
        [Required]
        [StringLength(300)]
        public string Medication { get; set; }
        [Required]
        [StringLength(30000)]
        public string MonitoringHealth { get; set; }
        [Required]
        [StringLength(300)]
        public string Eyesight { get; set; }
        [Required]
        [StringLength(300)]
        public string Hearing { get; set; }
        [Required]
        [StringLength(30000)]
        public string MentalAndEmotionalWellbeing { get; set; }
        [Required]
        [StringLength(30000)]
        public string DietaryNeeds { get; set; }
        [Required]
        [StringLength(30000)]
        public string EatingHabits { get; set; }
        [Required]
        [StringLength(30000)]
        public string DecisionMaking { get; set; }
        [Required]
        [StringLength(30000)]
        public string FoodPreferences { get; set; }
        [Required]
        [StringLength(30000)]
        public string FoodQuantities { get; set; }
        [Required]
        [StringLength(30000)]
        public string PersonalCare { get; set; }
        [Required]
        [StringLength(30000)]
        public string SleepingPattern { get; set; }
        [Required]
        [StringLength(30000)]
        public string HealthAndSafetyAwareness { get; set; }
        [Required]
        [StringLength(30000)]
        public string LanguageAndCommunication { get; set; }
        [Required]
        [StringLength(30000)]
        public string CulturalInformation { get; set; }
        [Required]
        [StringLength(30000)]
        public string CommunicatingPhysicalAndEmotionalCondition { get; set; }
        [Required]
        [StringLength(30000)]
        public string Sociability { get; set; }
        [Required]
        [StringLength(30000)]
        public string BehaviourPatterns { get; set; }
        [Required]
        [StringLength(30000)]
        public string LeisureAndCommunityParticipation { get; set; }
        [Required]
        [StringLength(30000)]
        public string EducationalAndVocationalAbilities { get; set; }
        [Required]
        [StringLength(30000)]
        public string FinanceAndMoneyManagement { get; set; }
        [Required]
        [StringLength(30000)]
        public string Other { get; set; }
    }
}
